# Generated by Django 4.2.7 on 2023-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(default='Pega el link de una imagen'),
        ),
    ]
